apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ckfn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0065-tenant/tkrw-pr714-0075-0065-app/devfile-sample-ckfn@sha256:ba305b4cd10a9780076cf4551b857ceed1f8bae979621f7409e8f342c026d7cb
        name: my-nodejs
        resources: {}
status: {}
